Update trigger_local_env.yml

diff --git a/.github/workflows/trigger_local_env.yml b/.github/workflows/trigger_local_env.yml
--- a/.github/workflows/trigger_local_env.yml
+++ b/.github/workflows/trigger_local_env.yml
@@ -23,26 +23,24 @@ jobs:
       - name: Wait for Local Env tests to pass
         run: |
           sleep 20
-          curl -s -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
-          https://api.github.com/repos/Yam1x/to-dos-local-env/actions/runs \
-          | jq '.workflow_runs | map(select(.event == "repository_dispatch" and .display_title == "trigger_from_UI")) | .[0]'
+          
 
-       #   #while true; do
-       #   STATUS=$(curl -s -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
-       #   https://api.github.com/repos/Yam1x/to-dos-local-env/actions/runs \
-        #  | jq '.workflow_runs')
+          while true; do
+            STATUS=$(curl -s -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
+            https://api.github.com/repos/Yam1x/to-dos-local-env/actions/runs \
+            | jq '.workflow_runs | map(select(.event == "repository_dispatch" and .display_title == "trigger_from_UI")) | .[0]')
 
 
-        #    echo "$STATUS"
+            echo "$STATUS"
 
-        #    if [ "$STATUS" == "\"success\"" ]; then
-        #      echo "Tests passed"
-        #      exit 0
-        #    elif [ "$STATUS" == "\"failure\"" ]; then
-        #      echo "Tests failed"
-        #      exit 1
-        #    fi
+            if [ "$STATUS" == "\"success\"" ]; then
+              echo "Tests passed"
+              exit 0
+            elif [ "$STATUS" == "\"failure\"" ]; then
+              echo "Tests failed"
+              exit 1
+            fi
 
-        #    echo "Waiting for test results..."
-        # # #  sleep 30
-        #  done
+            echo "Waiting for test results..."
+            sleep 30
+          done
