Update trigger_local_env.yml

diff --git a/.github/workflows/trigger_local_env.yml b/.github/workflows/trigger_local_env.yml
--- a/.github/workflows/trigger_local_env.yml
+++ b/.github/workflows/trigger_local_env.yml
@@ -22,7 +22,21 @@ jobs:
           
       - name: Wait for Local Env tests to pass
         run: |
-          curl -s -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
-          https://api.github.com/repos/Yam1x/to-dos-local-env/actions/runs \
-          | jq -r '.workflow_runs[] | select(.head_branch == "master") | .conclusion' | head -n 1
+          while true; do
+            STATUS=$(curl -s -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
+            https://api.github.com/repos/Yam1x/to-dos-local-env/actions/runs \
+            | jq '.workflow_runs[] | select(.head_branch=="master") | .conclusion' | head -n 1)  # Здесь всегда проверяем ветку "master"
 
+            echo "$STATUS"
+
+            if [ "$STATUS" == "\"success\"" ]; then
+              echo "Tests passed"
+              exit 0
+            elif [ "$STATUS" == "\"failure\"" ]; then
+              echo "Tests failed"
+              exit 1
+            fi
+
+            echo "Waiting for test results..."
+            sleep 30
+          done
