Update trigger_local_env.yml

diff --git a/.github/workflows/trigger_local_env.yml b/.github/workflows/trigger_local_env.yml
--- a/.github/workflows/trigger_local_env.yml
+++ b/.github/workflows/trigger_local_env.yml
@@ -1,14 +1,22 @@
 name: Trigger Local Env
 
 on:
-  push:
+  pull_request:
     branches:
-      - test
+      - master
+    types: [opened, synchronize, reopened]
 
 jobs:
   trigger:
     runs-on: ubuntu-latest
     steps:
+    
+      - name: Get the branch name from the PR
+        id: get_branch
+        run: |
+          echo "Branch name: ${{ github.head_ref }}"
+          echo "::set-output name=branch_name::${{ github.head_ref }}"
+
       - name: Send dispatch event
         env:
           GITHUB_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
@@ -17,4 +25,32 @@ jobs:
           -H "Accept: application/vnd.github.everest-preview+json" \
           -H "Authorization: token $GITHUB_TOKEN" \
           https://api.github.com/repos/Yam1x/to-dos-local-env/dispatches \
-          -d '{"event_type": "trigger_from_UI"}'
+          -d '{"event_type": "trigger_from_UI", "client_payload": {"branch_name": "${{ steps.get_branch.outputs.branch_name }}"}}'
+
+          
+      - name: Wait for Local Env tests to pass
+        run: |
+          sleep 20
+      
+          while true; do
+            STATUS=$(curl -s -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
+              https://api.github.com/repos/Yam1x/to-dos-local-env/actions/runs \
+              | jq '.workflow_runs | map(select(.event == "repository_dispatch" and .display_title == "trigger_from_UI")) | .[0].status')
+      
+            if [ "$STATUS" == "\"completed\"" ]; then
+              CONCLUSION=$(curl -s -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
+                https://api.github.com/repos/Yam1x/to-dos-local-env/actions/runs \
+                | jq '.workflow_runs | map(select(.event == "repository_dispatch" and .display_title == "trigger_from_UI")) | .[0].conclusion')
+      
+              if [ "$CONCLUSION" == "\"success\"" ]; then
+                echo "Tests passed"
+                exit 0
+              else
+                echo "Tests failed" 
+                exit 1
+              fi
+            else
+              echo "Waiting for test results..."
+              sleep 30
+            fi
+          done
